# Ejercicios Modulo 5. Librerías especializadas en datos 


#Ficheros: https://drive.google.com/file/d/1GmvppGuZSKafbMtCHyZl7myQipcv6Tf8/view?usp=sharing
#Ficheros: https://drive.google.com/file/d/1s4Q7NvKrkElillZmeDyl1-KAvbvKGCHj/view?usp=sharing

**1) Trabajemos con NumPy**

* Importa numpy y usa un alias para poder utilizar sus recursos
* Crea un array de elementos (del 10 al 100)
* Invertir el array
* Crear un array 3x3 con valores de 0 a 8
* Crear un array identidad de 6x6
* Crear un array con valores al azar con forma 3x3x3
* Crear dos arrays con valores al azar A y B, verificar si son iguales (hay varias opciones, investigar)

In [1]:
# Completa el ejercicio aquí
import numpy as np
temperaturas = np.array([17.25, 12.38, 10.6, 15.79, 14.27])
print(temperaturas)

temperaturas_inv = np.flip(temperaturas)
print(temperaturas_inv)

array1 = np.arange(0,9)
print(array1)
array2 = np.reshape(array1, [3,3])
print(array2)

array3 = np.arange(0,36)
print(array3)
array4 = np.reshape(array3, [6,6])
print(array4)

array_random1 = np.random.random((3,3,3))
print(array_random1)

a = np.array([[5, 7, 8], [1, 2, 6]])
b = np.array([[5, 9, 1], [4, 2, 8]])
print(a == b)
print((a == b).all())

[17.25 12.38 10.6  15.79 14.27]
[14.27 15.79 10.6  12.38 17.25]
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[[0.91767623 0.41749509 0.94701572]
  [0.89101413 0.98887158 0.09256761]
  [0.61524452 0.31690829 0.16636195]]

 [[0.37177193 0.91804678 0.68631577]
  [0.23030818 0.55709849 0.77730766]
  [0.72544392 0.27079253 0.79351485]]

 [[0.4591915  0.77425375 0.13737728]
  [0.43201021 0.39989334 0.72100278]
  [0.9523554  0.77331441 0.10526777]]]
[[ True False False]
 [False  True False]]
False


**2) Sigamos con NumPy**

* Crear un array de 100 elementos aleatorios comprendidos entre 1 y 1000 (pueden ser números enteros).
* Este array se llamara dólares
* Crear otro array llamado euros
* Realizar la conversión de los precios en dólares del primer array al segundo array en euros. Se puede serguir la siguiente conversión:
    - 1 EUR = 1,14362 USD
    - 1 USD = 0,874413 EUR
* Mostrar el resultado del array de euros pero redondeado a 2 decimales

In [2]:
# Completa el ejercicio aquí

import numpy as np
import random

print("Array Random dolares", "\n")
dolares = np.random.randint(1, 1000,100)
print(dolares, "\n")

print("Array Random euros", "\n")
euros = np.random.randint(1, 1000,100)
print(euros, "\n")

print("Conversion de Dolares a Euros", "\n")
dolares_euros = dolares * 0.874413
dolares_euros = np.around(dolares_euros, decimals=2)
print(dolares_euros, "\n")

print("Conversion de Euros a Dolares", "\n")
euros_dolares = euros * 1.14362
euros_dolares = np.around(euros_dolares, decimals=2)
print(euros_dolares, "\n")

Array Random dolares 

[916 452 679 301 168 799 189 365 451 459 373  71  85 321 903 266 868 596
 512 127 705 528 216 954 585 162 544 457  51 544 449 564 712 520 492 234
 365 129 884 673 284 128 290   4 974 463 965 387 199 554 190 894 308 439
 973 300 310 293 771 700 664 510 309 841 587 484 431 149 169 354 865 201
 459 383 721 583 303  67 447 650  80  99 371 981 535   3 512 696 508 101
 424 206 665 744 369 696 620 657 341  20] 

Array Random euros 

[319 385 308  82 730 781 700  43 649 159 368 341 483 641   8 726 241  93
  89 248 410 755 505 359 881 227 487 359 968 728 221 970 319 624 299  68
 988 456  89 278 415 269 576 599 441 739 814 962 586 278   6 824 520 174
 104 324 256 982  68 990 270 446  86 357 269 631 459 433 867 164  49 725
 880 162 201 970 775 709 951 963 128 329 296 125 972 114 851 133 893 971
 670 828 512 576 667 697   5 276 179 737] 

Conversion de Dolares a Euros 

[800.96 395.23 593.73 263.2  146.9  698.66 165.26 319.16 394.36 401.36
 326.16  62.08  74.33 280.69 789.59

**3) Trabajemos con pandas**

* Importa pandas y usa un alias para poder utilizar sus recursos
* Cargar como dataframe de pandas el csv 05_05_imdb_titulos.csv y mostrar sus 5 primeros registros
* Cargar como dataframe de pandas el csv 05_05_imdb_elenco.csv y mostrar sus 5 primeros registros
* Mostrar el número de registros del dataframe de titulos
* Mostrar el número de registros del dataframe de elenco
* Mostrar las 5 peliculas más antiguas del listado de titulos
* Mostrar las peliculas que en el titulo tienen la palabra "Dracula". También mostrar el número total de peliculas que coincidan con este requisito
* Mostrar los 10 titulos más comunes (que más se repiten)
* Mostrar cual fue la primer pelicula hecha titulada "Romeo and Juliet" 
* Listar todas las peliculas que contengan la palabra "Exorcist" ordenadas de la más vieja a la más reciente
* Mostrar cuantas peliculas fueron hechas en el año 1950
* Mostrar cuantas peliculas fueron hechas de 1950 a 1959
* Mostrar todos los roles o papeles que hubo en la pelicula "The Godfather". También mostrar el número total de coincidencias
* Mostrar el elenco completo ordenado por la clasificacion "n" de la pelicula "Dracula" de 1958
* Mostrar cuantos papeles de "Bruce Wayne" han sido hechos en la historia de las peliculas
* Mostrar cuantos papeles ha hecho "Robert De Niro" en su carrera
* Listado de papeles como protagonista (n=1) que tuvo el actor "Charlton Heston" en la década de los 60's, ordenado por año de forma descendente
* Mostrar cuantos papeles para actores hubo en la década de los 50's
* Mostrar cuantos papeles para actrices hubo en la década de los 50's

In [5]:
# Completa el ejercicio aquí

import pandas as pd

titulos = pd.read_csv("05_05_imdb_titulos.csv")
#primeros_titulos = print(titulos.head(), "\n")

elenco = pd.read_csv("05_05_imdb_elenco.csv")
#primeros_elenco = print(elenco.head(), "\n")

num_titulos = print(titulos.count(), "\n")
num_elenco = print(elenco.count(), "\n")

year_titulos = titulos['year']
print(type(year_titulos)) # Como se ve, temps es una serie de panda
titulos_antiguos5 = year_titulos.sort_values(ascending = True)
print(titulos_antiguos5[:5])

dracula = titulos[titulos["title"] == "Dracula"]
print(dracula)
dracula.count()

titulos_comunes = titulos.title.value_counts().head(10)

romeo_julieta = titulos[titulos["title"] == "Romeo and Juliet"].sort_values("year").head(1)
print(romeo_julieta)

exorcista = titulos[titulos["title"].str.contains('Exorcist', case = False)].sort_values("year")
print(exorcista)

peliculas_1950 = titulos[titulos["year"] == 1950].sort_values("year").count()
print(peliculas_1950)

peliculas_1950_1959 = titulos[titulos["year"].isin([1950, 1960])].sort_values("year").count()
print(peliculas_1950_1959)

padrino = elenco[elenco["title"] == "The Godfather"]
print(padrino)
padrino.to_csv("padrino.csv")

dracula_elenco = elenco
dracula_elenco = dracula_elenco[(dracula_elenco.title == "Dracula") & (dracula_elenco.year == 1958)] 
dracula_elenco = dracula_elenco.sort_values("n")
print(dracula_elenco)

bruce_wayne = elenco[elenco["character"] == "Bruce Wayne"].count()
print(bruce_wayne)

robert_deNiro = elenco[elenco["name"] == "Robert De Niro"].count()
print(robert_deNiro)

charlton_heston = elenco
charlton_heston = charlton_heston[charlton_heston.name == "Charlton Heston"]
charlton_heston = charlton_heston[charlton_heston.n == 1]
charlton_heston = charlton_heston[(charlton_heston.year >=1960) & (charlton_heston.year <= 1969)]
charlton_heston = charlton_heston.sort_values('year',ascending=False)
print(charlton_heston)

papeles_actores_50 = elenco[(elenco["type"] == "actor") & elenco["year"].isin([1950, 1960])].count()
print(papeles_actores_50)

papeles_actrices_50 = elenco[(elenco["type"] == "actress") & elenco["year"].isin([1950, 1960])].count()
print(papeles_actrices_50)


title    230407
year     230407
dtype: int64 

title        3564650
year         3564650
name         3564650
type         3564650
character    3564650
n            2206127
dtype: int64 

<class 'pandas.core.series.Series'>
13229     1894
103233    1898
133020    1899
51528     1900
195127    1900
Name: year, dtype: int64
          title  year
30479   Dracula  1992
35229   Dracula  1958
62596   Dracula  1999
94156   Dracula  1931
156968  Dracula  2019
184003  Dracula  1979
                   title  year
124702  Romeo and Juliet  1916
                                         title  year
88003                             The Exorcist  1973
49658                  O Exorcista de Mulheres  1974
118920     Satanico Pandemonium: La Sexorcista  1975
140519                Exorcist II: The Heretic  1977
220073                        Kung Fu Exorcist  1978
17375                         The Exorcist III  1990
132451                        Teenage Exorcist  1991
117797                 Exorcist: The